### ISSUE TITLE
Webhint Setup in Local Env not Working in OS X El Capitan

### ISSUE THREAD

**Issue by StarSheriff2** [microverseinc/linters-config#100]
Hi,

I would appreciate help setting up Webhint in my local env. I've tried following the HTML-CSS Guide, but it doesn't work.

My setup description:

OS: El Capitan version 10.11.6
Code Editor: VS Code, Version: 1.49.1
Node version: v14.7.0
NPM version: 6.14.7
Node Version Manager: (v0.35.3)

Every time I run `npx hint .` I get something like this:
![Screen Shot](https://user-images.githubusercontent.com/61250665/93948525-f07df980-fcfb-11ea-8515-b400729e5cfb.png)

or this:
![Screen Shot 2020-09-22 at 3 29 47 PM](https://user-images.githubusercontent.com/61250665/93948627-228f5b80-fcfc-11ea-92b8-820159b1b4c3.png)

When running this     ```
    npm install --save-dev hint@6.0.x
    ``` in the Terminal, as per the Guide for Linters setup [microverseinc /
linters-config](https://github.com/microverseinc/linters-config/tree/master/html-css), I get the following:
![Screen Shot 2020-09-22 at 3 28 28 PM](https://user-images.githubusercontent.com/61250665/93948732-6d10d800-fcfc-11ea-98de-fdda041efe1b.png)

I ran `npm init` in the local repo/directory. This created the **node_modules/** directory and the following two files:

* **package-lock.json**
* **package.json**

This didn't make much of a difference. I have tried this in 2 different repos and still nothing. 
I also tried this `npm i hint` to try installing the latest version of webhint, but still nothing. This is what I got after running it:
![Screen Shot 2020-09-22 at 5 57 17 PM](https://user-images.githubusercontent.com/61250665/93949024-253e8080-fcfd-11ea-80bb-e614753758c5.png)

I even tried installing npm globally on my root dir, by running this `npm install -g --save-dev hint@6.0.x`. It didn't work either. I got this: 
![Screen Shot 2020-09-22 at 8 53 03 AM copy](https://user-images.githubusercontent.com/61250665/93949242-9aaa5100-fcfd-11ea-8c8b-338746ae2de7.png)

Anybody else had this same issue? I wonder if it has something to do with my OS, as it's quite outdated (almost obsolete by now).

Hopefully, someone can show me how to fix this.

**P.S.**
I copied the` .hintrc` file to the root dir before running `npx hint`, and yes I ran `npm init` before the `npm install --save-dev hint@6.0.x` command.

My current `dependencies` section in the `package.json` file looks like this:
![Screen Shot 2020-09-22 at 6 05 27 PM](https://user-images.githubusercontent.com/61250665/93949633-61261580-fcfe-11ea-988c-078a01ea1dfa.png)

**Comment by shshamim63** [comment]
Hi @StarSheriff2 :wave: 
Thanks for opening the issue. I believe webhint is working properly. Actually there are no errors in your code. That is why as a result it renders
![image](https://user-images.githubusercontent.com/61250665/93948525-f07df980-fcfb-11ea-8515-b400729e5cfb.png)
Now if you want to check that can catch any error, you can try an example. If you have any button tag in your HTML. please remove its type option and run `npx hint .`. You will see an error similar to the following.
![image](https://user-images.githubusercontent.com/38625956/93980075-f88f7500-fd9f-11ea-9f95-a802062c938b.png)

**Comment by StarSheriff2** [comment]
Hi Shakhawat.

I tried the button with no type attribute test and still nothing.

Here's my repos "feature-branch" link: [](https://github.com/StarSheriff2/Technical-Documentatio-FCC-Project/tree/feature-branch-TDP)

Thanks for your help!

**Comment by bolah2009** [comment]
Hi @StarSheriff2 
Can you post this issue on https://questions.microverse.org/ seems to be the best place for it.
I will close this issue, however, @shshamim63 can still continue helping you with it.
Thanks.
