### ISSUE TITLE
Linter check doesn't work with set permissions for OOP project build on Windows OS

### ISSUE THREAD

**Issue by uryelah** [microverseinc/linters-config#105]
In the first milestone of the Ruby OOP project, where the bin/main file needs to be made executable with a shebang line the linter outputs errors if the project was built on a WIndows OS machine:
![Screenshot_2020-10-16 jcy2704 oop_ruby](https://user-images.githubusercontent.com/16193212/96310114-146fea80-0fdd-11eb-8472-82944a4abfb4.png)
Changing the .git/config filemode option to true doesn't seem to work.

The check only passes if the line: `chmod 755 bin/main` is passe to the linters config file inside github/workflows before running `-f  .rubocop.yml`
![Screenshot_2020-10-16 Wtf by uryelah · Pull Request #3 · jcy2704 oop_ruby](https://user-images.githubusercontent.com/16193212/96310295-7e888f80-0fdd-11eb-8e92-d4c64f5805f6.png)

What would be a better way to have the linters pass checks for Windows users without changing the config files?
@shshamim63

**Comment by Spayco** [comment]
the `chmod 775 bin/main` wouldn't help, it *does* work, but since this file will be used across all project, it might create a problem

i tested that chmod when the file doesn't exist, and it gives an error

**Comment by uryelah** [comment]
We might need to make using WSL obligatory for Windows users if there's no other way.

**Comment by Spayco** [comment]
after some digging, found a simple solution which is to update the file through `git`

using `git update-index --chmod=+x .\lib\main` then git add, commit and push would solve the problem

**Comment by shshamim63** [comment]
Hi @uryelah and @Spayco 
Can I get the PR so that I can also apply some changes, please?

**Comment by Spayco** [comment]
@shshamim63 we haven't made a PR for this, but I've made an MR in the guidelines [here](https://gitlab.com/microverse/guides/tse/code_review/code_review_guidelines/-/merge_requests/249)

**Comment by shshamim63** [comment]
I think renaming the file main.rb will resolve the issue. If you check the instruction in the pathwright it mentions main.rb and for bash command, it asks for bin/main.rb. Can you please confirm renaming the file resolves the issue or not?
![image](https://user-images.githubusercontent.com/38625956/96441337-2fd03500-122b-11eb-9907-461f2bf44f17.png)

**Comment by uryelah** [comment]
@shshamim63 Changing the file name, including the `.rb` extension at its end, does not help in this case, the error still shows up.

**Comment by shshamim63** [comment]
@uryelah may I have the PR/repo, please?

**Comment by uryelah** [comment]
Origin PR: 
https://github.com/jcy2704/oop_ruby/pull/1

You can notice in the commits that the student tried adding the extension and it still did not work.

**Comment by uryelah** [comment]
@shshamim63 
Origin PR: 
https://github.com/jcy2704/oop_ruby/pull/1

You can notice in the commits that the student tried adding the extension and it still did not work.

**Comment by bolah2009** [comment]
Hi @shshamim63 @uryelah 
What is the final decision on this?

**Comment by uryelah** [comment]
@bolah2009 @shshamim63 
Since the command that fixes this( `git update-index --chmod=+x .\lib\main`) issue is not compatible with Macs and really mostly useful for Windows users,
let's simply add it to the PathWright info on the TicTacTow ruby project Pathwright and maybe as a note to the Ruby linter instructions as mentioned [here](https://gitlab.com/microverse/guides/tse/code_review/code_review_guidelines/-/merge_requests/249).

**Comment by jcy2704** [comment]
I think the best way is to use `git update-index --chmod=+x  ./bin/main` for Windows and maybe for some of Linux, because I installed Linux Ubuntu 20.4 in a old computer and tried and it gives me the same error. 

Also sometimes when using `git update-index --chmod=+x  ./bin/main` it throws an error saying that is found or not accessible then just add `--add` after `--chmod=+x`

**Comment by uryelah** [comment]
I'm closing this issue since it's already being handled at the pathwright and code review instructions repo.
