### ISSUE TITLE
Eslint import plugin version not working in github actions for REACT

### ISSUE THREAD

**Issue by mateomh** [microverseinc/linters-config#114]
There is a problem with the GitHub actions that make the **eslint** linter run fail every time when working with REACT.
The error given by GitHub is the following:

![image](https://user-images.githubusercontent.com/66382067/99275865-01c61c80-27fa-11eb-91e5-b67c28085899.png)

After looking for a solution I found that the problem was with the eslint import plugin version 2.20 that needs a different parameter for the no-cycle rule. This error happens locally as well.

When the version is changed for 2.22, the error is fixed in both environments.

This only happens with the code created by the create-react-app command, regular JS code is not affected by it

**Comment by bolah2009** [comment]
This has been fixed in https://github.com/microverseinc/linters-config/pull/113 thanks to @bertil291utn
