### ISSUE TITLE
Error with an ESLint rule, directly on Github

### ISSUE THREAD

**Issue by NewIncome** [microverseinc/linters-config#118]
There is a problem with a rule and I cannot modify it because the node_modules files are being checked from somewhere else on Github. On my machine it's already solved in 2 different ways fine.
Please help with this. This should be inserted somewhere directly in the files or the code we download from this repo.

![Screenshot from 2020-11-27 16-00-19(eslint error on Github)](https://user-images.githubusercontent.com/42077060/100486856-856dec00-30cb-11eb-8512-e44b367a9bc4.png)

**Comment by bolah2009** [comment]
This has been fixed in https://github.com/microverseinc/linters-config/pull/113 thanks to @bertil291utn
