### ISSUE TITLE
comparing WebHint vs HTMLHint

### ISSUE THREAD

**Issue by Spayco** [microverseinc/linters-config#120]
as discussed on slack, I made a deep look into whether HTMLHint has everything WebHint has, so here's the result:

_p.s: I'm comparing the current rules set vs HTMLHint + inline style since that's what this is all about_

| Hint | Description |WebHint | HTMLHint|
| --- | --- | --- | --- |
| button-type | requires to use `type` attribute in a `<button>` tag | [available](https://github.com/webhintio/hint/tree/0166c4078eacb94ea475e0857a0a066ae77f7625/packages/hint-button-type) | unavailable |
| disown-opener | checks if the rel attribute is specified with both the `noopener` and `noreferrer` values (or only noopener if all the targeted browsers support it) on `<a>` and `<area>` elements that have `target="_blank"` and link to other origins | [available](https://github.com/webhintio/hint/blob/0166c4078eacb94ea475e0857a0a066ae77f7625/packages/hint-disown-opener/README.md) | unavailable |
| html-checker | validates the markup of a website against the [Nu HTML checker](https://validator.github.io/validator/) | [available](https://github.com/webhintio/hint/blob/0166c4078eacb94ea475e0857a0a066ae77f7625/packages/hint-html-checker/README.md) | unavailable |
| meta-charset-utf-8 | checks if the page explicitly declares the character encoding as utf-8 using a meta tag early in the document | [available](https://github.com/webhintio/hint/blob/0166c4078eacb94ea475e0857a0a066ae77f7625/packages/hint-meta-charset-utf-8/README.md) | unavailable |
| meta-viewport | warns against not having a single viewport meta tag in the `<head>` with the proper value. | [available](https://github.com/webhintio/hint/blob/0166c4078eacb94ea475e0857a0a066ae77f7625/packages/hint-meta-viewport/README.md) | unavailable |
| inline-style-disabled | forbid the use of inline stylings | unavailable | [available](https://htmlhint.com/docs/user-guide/rules/inline-style-disabled) |

**Sources**: [WebHint Hints](https://github.com/webhintio/hint/tree/0166c4078eacb94ea475e0857a0a066ae77f7625/packages) || [HTMLHint Rules](https://htmlhint.com/docs/user-guide/list-rules)

so I guess the best approach here, is to use both, HTMLHint has some more useful rules that can be used as well (check sources)

**Comment by bolah2009** [comment]
@Spayco  what other features are needed that HTMLHints has and Webhint doesn't? 🤔

**Comment by Spayco** [comment]
Hey @bolah2009 

something like `title-require`, `attr-no-duplication`, `inline-style-disabled` can be helpful

**Comment by bolah2009** [comment]
I think `title-require` and `attr-no-duplication` should be valid with webhint's HTMLChecker. I opened a PR for the inline styles, hopefully, it should get merge soon so we can add the config to the webhint config.

**Comment by bolah2009** [comment]
`inline-style-disabled` is not available in webhint. See https://github.com/webhintio/hint/pull/4161 and https://github.com/webhintio/hint/pull/4257

**Comment by Spayco** [comment]
@bolah2009 do you mean it's **available**? cause I'm seeing the PRs are merged

**Comment by bolah2009** [comment]
Yes, sorry. I mean it's available. Please can you open a PR to include this version?

**Comment by Spayco** [comment]
will do @bolah2009
