### ISSUE TITLE
Version for eslint-plugin-import may need to be updated to ^2.22.1

### ISSUE THREAD

**Issue by Joseph-Burke** [microverseinc/linters-config#122]
Using the npm install commands for ESLint in the react-redux module produced an error for me when I tried to run `npx eslint .`:

> Configuration for rule "import/no-cycle" is invalid:
        Value "∞" should be integer.

I fixed this issue by upgrading the version of `eslint-plugin-import` in my `package.json`, and it then worked fine. The version I updated to was

`"eslint-plugin-import": "^2.22.1"`

Perhaps the linter setup instructions should be modified to avoid this error in future?

**Comment by bolah2009** [comment]
This has been fixed in https://github.com/microverseinc/linters-config/pull/113 thanks to @bertil291utn
