### ISSUE TITLE
React Linters yml should be eslint-plugin-import@2.22.x rather than 2.20

### ISSUE THREAD

**Issue by gurbuzertunga** [microverseinc/linters-config#130]
on version 2.20 you get the following error

`Error: .eslintrc » eslint-config-airbnb » //node_modules/eslint-config-airbnb-base/index.js » //node_modules/eslint-config-airbnb-base/rules/imports.js: Configuration for rule "import/no-cycle" is invalid: Value "∞" should be integer.`

**Comment by bolah2009** [comment]
This issue has been resolved in https://github.com/microverseinc/linters-config/pull/113. Closing this.. thanks 🙂
