### ISSUE TITLE
EXTEND STYLELINT TO RECOGNIZE NEW METHODS

### ISSUE THREAD

**Issue by RamseyNjire** [microverseinc/linters-config#131]
While working on the [`ror-social-scaffold`](https://github.com/microverseinc/ror-social-scaffold) project, I came across an issue where Stylelint would flag the `fit-content` value for the `width` property as an error. I researched it and found out it was a [known issue](https://github.com/csstree/stylelint-validator/issues/29). I opened an issue on the `ror-social-scaffold` project [here](https://github.com/microverseinc/ror-social-scaffold/issues/296). Later, I fixed the issue via [this pull request](https://github.com/microverseinc/ror-social-scaffold/pull/297). One of the suggestions by @bolah2009 and @uryelah was to open an issue on the same here so we can extend the solution to this repo. If it's okay with the maintainers we can extend the CSS dictionary in the .stylelintrc.json file here as well.

**Comment by bolah2009** [comment]
@uryelah can you do this?

**Comment by bolah2009** [comment]
@RamseyNjire if you have the time please go ahead and open a PR.

@Spayco can you open a PR for this if @RamseyNjire can’t? See https://github.com/microverseinc/ror-social-scaffold/pull/297 as similar changes.

**Comment by RamseyNjire** [comment]
@bolah2009 Done! You can find the pull request [here](https://github.com/microverseinc/linters-config/pull/143).

**Comment by RamseyNjire** [comment]
Closing the issue since the above matter has already been handled.
