### ISSUE TITLE
Update HTML/CSS Documentation

### ISSUE THREAD

**Issue by arthurborgesdev** [microverseinc/linters-config#133]
Add to the documentation a bullet point for this:

`npm init`

before installing the linters. Otherwise, there may be conflicts on each run of the linters.

**Comment by Spayco** [comment]
could you explain more/give an example @arthurborgesdev?

**Comment by arthurborgesdev** [comment]
When I run the commands before initializing the package.json file, I get errors, see:

1 - Run npm install --save-dev hint@6.0.x (Prompt in the documentation):

![image](https://user-images.githubusercontent.com/38326017/111790477-ff0b2f00-88a0-11eb-8ceb-53735247d5bf.png)

2 - The package is installed, but it does not generate a package.json file per si:

![image](https://user-images.githubusercontent.com/38326017/111790718-42fe3400-88a1-11eb-95a3-a9954016782e.png)

3 - Although... as I can see now, the `npx hint .` run correctly even without running npm init at the beginning... strange. I don't know what I did on the first try that made me switch to the `npm init` approach... 

![image](https://user-images.githubusercontent.com/38326017/111791180-bb64f500-88a1-11eb-8920-b05e55ed48e5.png)


I will close the issue, thank you!

**Comment by Spayco** [comment]
@arthurborgesdev happy you solved your issue, yes it's not needed to have the `package.json` (which what `npm init` will do)
