### ISSUE TITLE
Unable to find Ruby version 3.0.0

### ISSUE THREAD

**Issue by tadeuasarro** [microverseinc/linters-config#137]
#### I just updated the Rubocop version to 1.11 in line 19 and it worked just fine.

:D

**Comment by Spayco** [comment]
hey, just to be clear, are you suggesting updating the rubocop version on the instructions for rubocop?
if yes, could you do a PR for it? 

also, does Rubocop version 1.11 works on older ruby versions?

**Comment by tadeuasarro** [comment]
Just wanted to create some documentation in case someone would find themselves in the same position as I did.

Also, I didn't try with older Rubocop 1.11 with older Ruby versions.

**Comment by bolah2009** [comment]
Closing this as it's not an issue, @tadeuasarro you can add this to discourse.

@Spayco This is related to what I suggested in https://github.com/microverseinc/linters-config/pull/142

**Comment by bolah2009** [comment]
Also, @Spayco this is solved for Ruby projects in https://github.com/microverseinc/linters-config/pull/126/files by @uryelah
