### ISSUE TITLE
ESLINT "no-use-before-define" should be disabled

### ISSUE THREAD

**Issue by kunmi02** [microverseinc/linters-config#138]
_In JavaScript, prior to ES6, variable and function declarations are hoisted to the top of a scope, so it’s possible to use identifiers before their formal declarations in code. This can be confusing and some believe it is best to always declare variables and functions before using them._

reference [stackoverflow](https://stackoverflow.com/questions/56499552/for-what-purpose-no-use-before-define-warns-about-declared-functions)

Like this:

```
"rules": {
    "no-shadow": "off",
    "no-param-reassign": "off",
    "eol-last": "off",
    "arrow-parens": "off",
    "no-use-before-define":"off"
  },
```

Since we are going with the ES6 format, coders should be given the flexibility to extend their creativity hence why the no-use-before-define need to be disabled

Please let me know if there is a reason for it not to be disabled

**Comment by Spayco** [comment]
in the same article you provided:

> **This can be confusing and some believe it is best to always declare variables and functions before using them.**

linters are all about readability, and it's going to be confusing for the reader to see a function that wasn't declared, and would assume it's on the top but can never find it.

> coders should be given the flexibility to extend their creativity hence why the no-use-before-define need to be disabled

could you provide an example?

**Comment by Spayco** [comment]
this has been waiting for more than 10 days, also I don't think it's a good thing to disable `no-use-before-define`, so I'm closing this issue, you can always still reply if you think there's a need for this.
