### ISSUE TITLE
Getting error while installing eslint-config-airbnb plugin for ESLint.

### ISSUE THREAD

**Issue by RaminMammadzada** [microverseinc/linters-config#141]
During the linter config in my redux based project I am facing the problem related to Eslint config installation.

When I run `npm install --save-dev eslint@7.11.x eslint-config-airbnb@18.1.x eslint-plugin-import@2.22.x eslint-plugin-jsx-a11y@6.2.x eslint-plugin-react@7.20.x eslint-plugin-react-hooks@2.5.x babel-eslint@10.1.x` , I am getting this error:

```
Debugger attached.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-bookstore-cms@0.1.0
npm ERR! Found: eslint@7.11.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.11.x" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0" from eslint-config-airbnb@18.1.0
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"18.1.x" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/dere/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dere/.npm/_logs/2021-03-22T19_38_55_657Z-debug.log
Waiting for the debugger to disconnect...
```
I have created the project with `create-react-app` script. Even to solve the problem, I removed package-lock.json file and run `npm install` again too. It didn't solve the problem.

**Comment by Spayco** [comment]
Hello, we're working on a fix for all these issues, and we'll be updating everything to work with npm 7, for the time being, please either downgrade to npm v6, or use `npx -p npm@6 npm install` (then the packages listed)
