### ISSUE TITLE
selector-type-case error on a .js file

### ISSUE THREAD

**Issue by Mupa1** [microverseinc/linters-config#145]
### selector-type-case error on a .js file

- I get this Stylelint error when I use a .js file for material-ui.

<img width="734" alt="Screen Shot 2021-03-31 at 11 53 25" src="https://user-images.githubusercontent.com/44979953/113127118-ad579280-9218-11eb-844f-43ef9efa337e.png">

- However, if I omit styles on @material-ui/core/styles as shown on the screenshot below, I don't get the Stylelint errors.

<img width="438" alt="Screen Shot 2021-03-31 at 14 09 47" src="https://user-images.githubusercontent.com/44979953/113412139-d19da580-93b7-11eb-8581-bf749a298cdb.png">

**Comment by Spayco** [comment]
@bolah2009 you think we should add a note about this kind of issue, or should you ignore JS files for stylelint? 🤔

**Comment by bolah2009** [comment]
@Spayco let's ignore  js files. But this shouldn't be an issue since stylelint config only checks CSS and SCSS files.
