### ISSUE TITLE
Error with Rubocop on branch.

### ISSUE THREAD

**Issue by carlos-ssh** [microverseinc/linters-config#148]
Run rubocop --color
  rubocop --color
  shell: /bin/bash -e {0}
  env:
    FORCE_COLOR: 1
Error: RuboCop found unknown Ruby version 3.0 in `/home/runner/work/The_BookShelve/The_BookShelve/Gemfile.lock`.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7
Error: Process completed with exit code 2.

**Comment by Spayco** [comment]
@carlos-ssh  can you give more details? 

- [ ] give us the repo link
- [ ] tell us how to reproduce this issue

**Comment by Spayco** [comment]
but it looks like rubocop doesn't support ruby 3.0.0

**Comment by carlos-ssh** [comment]
Here is the[ Link](https://github.com/carlos-ssh/The_BookShelve/pull/1) for the branch project.
I fixed this issue by changing this code: `env:
FORCE_COLOR: 1` to `env:
FORCE_COLOR: 0`

By now my Linters are running well!
Cheers!
