### ISSUE TITLE
Add aditional module on linters.yml for React-redux

### ISSUE THREAD

**Issue by vichuge** [microverseinc/linters-config#152]
I had an issue concerning this, the reason was a module that wasn't in the linter.yml config, this was `@babel/preset-env`.
When I worked on react calculator test, I had issues regarding babel and jest, the solution was to install some babel modules on my project. The test works perfectly (linters locally too) but I had issues with linters in the GitHub page only, locally works well.

I add this module on my linters.yml and I solved the issue, I add the PR here for inspection:
[my PR](https://github.com/vichuge/react-calculator/pull/10)

![image](https://user-images.githubusercontent.com/20563252/122295769-3c428580-cebf-11eb-9a13-fccf945f9f40.png)
![image](https://user-images.githubusercontent.com/20563252/122296042-8f1c3d00-cebf-11eb-9248-a768e61281c5.png)

**Comment by Spayco** [comment]
Thanks for the information!

I added the package on #153 to fix this
