### ISSUE TITLE
Warning in .rubocop.yml

### ISSUE THREAD

**Issue by Hombre2014** [microverseinc/linters-config#184]
Running the current version of .rubocop.yml file there are a couple of Warnings:
On line 10:
.rubocop.yml: Layout/LineLength has the wrong namespace - should be Metrics
and on line 47:
.rubocop.yml: Style/HashEachMethods has the wrong namespace - should be Performance

They should be changed to:
10. Metrics/LineLength:
.
.
47. Performance/HashEachMethods:

**Comment by bellom** [comment]
Thank you @Hombre2014, the Ruby project has been updated, hence we don't face the issue of length anymore, let me know what you think with full details from you.

I will close this PR in a few days.

**Comment by Hombre2014** [comment]
Thanks @bellom
