### ISSUE TITLE
¡¡¡¡¡IMPORTANT!!!

### ISSUE THREAD

**Issue by sergiogval** [microverseinc/linters-config#185]
# Well done so far. I can even say that i'm proud about you.

That said there are a HUGE holes in your code. Can you fix them right the way, please?
this is part of the evidence...
![Web capture_4-3-2022_14146_github com](https://user-images.githubusercontent.com/67393791/156904123-df691dd4-0a60-486a-95d1-acbb77a7e7f4.jpeg)
Also, I noticed that you deleted all the work I've done so far. Not to mention that you explicitly avoided mentioning in the ISA, that little stuff named gitcoin and this seems to belong to a .gov domain... I consider that very unfair. @arielcamus @amalbepo @anneloredevreese @gootyfer.

One last thing... Maybe you can try to wash your hands by delating everything. But I'm surprised that you don't know it takes 1 month to be cleaned on the github server. 

As a gift, a second peace of evidence.
![image](https://user-images.githubusercontent.com/67393791/156904230-869da861-0683-4f39-89f7-06fdf09d8c92.png)
@kethinov @jjmata

If you have any doubts or commentaries, please don't hesitate to reach me out.

HAPPY CODING!!! 💯

**Comment by nidalaa** [comment]
Hello @sergiogval ,

>That said there are a HUGE holes in your code. Can you fix them right the way, please?
this is part of the evidence...

In the screenshots, I can only see links to the linters config files that are hosted in this repo, for example, https://github.com/microverseinc/linters-config/blob/master/html-css-js/.hintrc, and they are completely safe.

Can you elaborate on what hole you have in mind?

-------

>Also, I noticed that you deleted all the work I've done so far. Not to mention that you explicitly avoided mentioning in the ISA, that little stuff named gitcoin and this seems to belong to a .gov domain... I consider that very unfair.

What do you mean by deleting all the work you have done so far? Any pull request in this repo? I cannot see any contributions from you.

I am also super confused with gitcoin - what are you referring to?

**Comment by sergiogval** [comment]
Yes, I believe you are missing the second image. That one belongs to the PR with the patches to solve the malware. Can you dig a little more into them or would you like me to explain that? also I got some interesting evidence where hint uses node-fetch as sub dependency. node-fetch is well known for having a high severity vulnerability. If you want to, I will be more than happy to give you the specific.

**Comment by sergiogval** [comment]
about gitcoin, well here you can find it.
![image](https://user-images.githubusercontent.com/67393791/157061176-8c3eb66d-38e1-493a-9a02-64cddbd93a3a.png)

**Comment by sergiogval** [comment]
@nidalaa please, this is important. If you can't see this page in your end. I don't Know if you are naive or faking don't know about it. Both cases are bad.

**Comment by sergiogval** [comment]
OK. Close it. I appreciate your attention.
