### ISSUE TITLE
Extra character on eslint command

### ISSUE THREAD

**Issue by kosher9** [microverseinc/linters-config#192]
There is an extra character at the end of the eslint install command preventing it from running. 
![eslint_extra_cararcc](https://user-images.githubusercontent.com/34873327/167513128-74f65edd-870f-4547-b433-d0d182247f22.png)

**Comment by MarcoOquendoC** [comment]
Yes. It is in the README.md file. 
I almost open a new issue.

**Comment by kosher9** [comment]
All right 👍🏾. I noticed that I was not able to run the command without removing it. I never tried it again since then.

**Comment by kosher9** [comment]
I should close the issue right?

**Comment by MarcoOquendoC** [comment]
Don't close it. I believe it will be done by the person who is maintaining this repo.

**Comment by bellom** [comment]
Thank you @kosher9

**Comment by kosher9** [comment]
Okay then.
