### ISSUE TITLE
Ubuntu 18.04 depreciation

### ISSUE THREAD

**Issue by teckim** [microverseinc/linters-config#205]
Today I tried to submit a pull request for a Ruby project, and the GitHub action was failing, after doing some investigation, it turned out that the actions are configured to run on `Ubuntu 18.04` which was started to be deprecated on 8/8/22 as this official [GitHub Action issue](https://github.com/actions/runner-images/issues/6002#issue-1325639357) announced 20 days ago.

I tried updating the configuration in my project by changing `runs-on: ubuntu-18.04` to `runs-on: ubuntu-20.04` and then everything seemed to be fine.

I will try to follow up with a pull request to solve this issue.

**Comment by bellom** [comment]
Issue fixed
