### ISSUE TITLE
linters.yml file throws "Lighthouse" error

### ISSUE THREAD

**Issue by PrantoshB** [microverseinc/linters-config#229]
Hello Team 👋,

I can see almost every day new Micronauts to React Module Students are complaining about `LightHouse error` on Slack after creating a PR on GitHub. I have noticed that changing the `node-version` for LightHouse to `12.x`  from `18.x` solves the issue.
So, what do you think? Should it be changed inside the `linters.yml` file?

Thanks 🍻
Prantosh

**Comment by NoerGitKat** [comment]
Hello @PrantoshB,

We have recently updated our linter configs so this error should not be happening anymore.

Please let us know what your experiences are.

Noer
**Technical Curriculum Designer**
