### ISSUE TITLE
Remove Template Literal

### ISSUE THREAD

**Issue by ohyajk** [microverseinc/linters-config#230]
https://github.com/microverseinc/linters-config/blob/b42cdb9ad2207da40329f3f655928742525c564f/ruby/.rubocop.yml#L1

The template literal cause error in Ruby project. Please remove it.
![ruboerror](https://user-images.githubusercontent.com/114587346/222079280-8d14208c-17c4-4cfd-8d79-abac2e0e1d39.png)

**Comment by michaelamponsah** [comment]
### I encountered a similar issue. @microverseinc/curriculum-content, please resolve this issue. 

#### Thank you.

**Comment by NoerGitKat** [comment]
This issue has been resolved, so closing it. Thanks @ohyajk & @michaelamponsah !
