### ISSUE TITLE
.rubocop.yml 

### ISSUE THREAD

**Issue by Uthmanbello** [microverseinc/linters-config#237]
There is a backtick located at the beginning of the `.rubocop.yml` file on the line below:

https://github.com/microverseinc/linters-config/blob/8dff3624362e6aaebadb322d09449a20d58bae00/ruby/.rubocop.yml#L1

When one tries to fix errors using the file, it creates some issues. Please, I will like the team to look into it.
Thanks ❤️

**Comment by NoerGitKat** [comment]
Thanks for mentioning, @Uthmanbello . It has been resolved (see [here](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml)), so closing this!

**Comment by Uthmanbello** [comment]
Ok. Thanks a lot
