### ISSUE TITLE
Outdated Ruby linter

### ISSUE THREAD

**Issue by BugInsertor** [microverseinc/linters-config#247]
Hello,

My team and I are working on the Ruby capstone project

And we think that the linters files of ruby are misconfigured according to GitHub

https://github.com/Al-Amin-Khan-Shakil/ruby-group-capstone-project/actions/runs/6932107932/job/18855303068?pr=45

The problem is in ".rubocop.yml" file, which we are instructed to not edit

![Screenshot from 2023-11-20 16-18-32](https://github.com/microverseinc/linters-config/assets/48357105/b04c7e7d-4f93-4da8-a5dc-0277c23c51cf)

**Comment by nidalaa** [comment]
Hi @Goldinium ,

I can see that rubocop is complaining about empty file in your repo. It look like it works as it should. Did you try to remove the empty file?
