### ISSUE TITLE
CLI for running https://validator.w3.org/

### ISSUE THREAD

**Issue by MauricioRobayo** [microverseinc/linters-config#25]
Might be good to include on the README.md for the HTML/CSS module that there is a CLI for running the [w3 validator](https://validator.w3.org/), so we don't have to copy/paste the HTML files on the page to get the validation: [html-validator-cli](https://github.com/zrrrzzt/html-validator-cli), which is using the [w3 validator API](https://validator.w3.org/docs/api.html).

The fewer steps are between a tool and the user the more probable she/he is going to use it. So having that option might be a good improvement in the development workflow and toolbox.

If this seems to be a good idea, I'll be glad to update the README.md to include the info with installation instructions and make the PR.

**Comment by nidalaa** [comment]
Go ahead @MauricioRobayo !


Let's agree on the structure first:
- new html_validator directory
- link to new htm_validator in main README

**Comment by gootyfer** [comment]
Hi @MauricioRobayo ! Please, work on the PR when you had some time.
I think that for the first version the w3c validator is good enough. But I really liked this webhint tool that also addresses accesibility and performance validation 🙌We should definitely use it in the future!
