### ISSUE TITLE
Obsolete configuration found in .rubocop.yml

### ISSUE THREAD

**Issue by stiakov** [microverseinc/linters-config#43]
https://github.com/microverseinc/linters-config/blob/fdc10990873bfc6e9577e8bc4da8aec5500e78d4/ror/.rubocop.yml#L44

Trying to run `rubocop` on the command line and using a project based on **Ruby 2.7.0** and **Rails 6.0.2** it throws me this error:

> Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
> (obsolete configuration found in .rubocop.yml, please update it)

![Screen Shot 2020-01-15 at 10 56 20 PM](https://user-images.githubusercontent.com/1456388/72492192-553a9900-37ea-11ea-87e3-9746473ea1c0.png)

**Comment by stiakov** [comment]
Should I submit a pull request for it?

**Comment by nidalaa** [comment]
@stiakov thanks for report, I went ahead and created a PR https://github.com/microverseinc/linters-config/pull/45. The next time to not hesitate to open PR immediately :)
