### ISSUE TITLE
wrong namespace for Rubocop

### ISSUE THREAD

**Issue by stiakov** [microverseinc/linters-config#44]
https://github.com/microverseinc/linters-config/blob/fdc10990873bfc6e9577e8bc4da8aec5500e78d4/ror/.rubocop.yml#L13

Running `rubocop` I'm getting this warning: 

> .rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout

![Screen Shot 2020-01-15 at 11 14 42 PM](https://user-images.githubusercontent.com/1456388/72492872-c8dda580-37ec-11ea-92ca-381b0fc4a4d4.png)

**Comment by nidalaa** [comment]
@stiakov thanks for report, I went ahead and created a PR https://github.com/microverseinc/linters-config/pull/45. The next time to not hesitate to open PR immediately :)
