### ISSUE TITLE
[JS] Eslint installation needs to state that `package.json` is needed

### ISSUE THREAD

**Issue by Israel-Laguan** [microverseinc/linters-config#51]
# Problem
In my javascript project (a [Template Repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template), BTW):
![image](https://user-images.githubusercontent.com/36519478/73144919-47053c00-4078-11ea-8ee3-7544de9b6f71.png)

I tried to run `npx eslint .` and I found the follow error:
![image](https://user-images.githubusercontent.com/36519478/73144958-98153000-4078-11ea-89b4-84532fb5d9b2.png)

After battle some minutes I found that *its mandatory to have a `package.json` in the folder*, which is not stated on the README explicitly.

This lack of information can mislead certain students, as for some of them maybe this is the first contact with `nodejs`, `npm` or `npx`.

# Proposal

Modify the instructions in this [section]() to add after these line:
![image](https://user-images.githubusercontent.com/36519478/73145554-35be2e80-407c-11ea-9cce-fd0d8f7290f9.png)

Something like:
> run `npm --init `, answer the questions to generate a `package.json` that store the info needed for NodeJS to start your project. You can modify this file later to fit your needs. Also create a `.gitignore` with `node_modules` inside.

Then the next step (`npx eslint --init`) must work normally.

**Comment by nidalaa** [comment]
Hi @Israel-Laguan !

It looks like your issue has been solved in this PR https://github.com/microverseinc/linters-config/pull/50.

Big 👏  to @jofer86 !
