### ISSUE TITLE
[JS] Linter rule about `.js` extensions make some code unusable

### ISSUE THREAD

**Issue by Israel-Laguan** [microverseinc/linters-config#52]
# Problem
When I use the provided eslint rules in my project without nodejs/webpack this error shows on the browser:
FIREFOX
![image](https://user-images.githubusercontent.com/36519478/73177830-ff190000-40dd-11ea-83a5-108b186c1667.png)
CHROME:
![image](https://user-images.githubusercontent.com/36519478/73178982-6a63d180-40e0-11ea-8455-90f8e839efb0.png)

As microverse uses `airbnb-base`:
https://github.com/microverseinc/linters-config/blob/8ea3768aaa671cc97b200af8feb037bcc1ded585/javascript/.eslintrc.json#L11

...and this rules states that not showing extensions are enforced:

https://github.com/airbnb/javascript/blob/6d05dd898acfec3299cc2be8b6188be542824965/packages/eslint-config-airbnb-base/rules/imports.js#L139-L143

**But browsers don't get files without extension**, as showed on my screen and here:
https://stackoverflow.com/a/55289496/9948644

When I added extensions error disappeared from browser and code run normally.

This is important because in the first projects (and maybe test or vanillaJS code) we won't have Nodejs and ES support, and some juniors can be locked with this instead of business code.

# Proposal

For the first 2 projects (when we don't use webpack) let us add to our copy of the [microverse' JavaScript rules](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json): 

```json
"rules": {
    "import/extensions": [
            "error",
            "ignorePackages",
            {
              "js": "always"
            }
    ]
}
```

On the remain projects use the rules as normal.

**Comment by frederico-miranda** [comment]
@Israel-Laguan 

"But browsers don't get files without extension" — Browsers do get files without extension. What truly matters for a browser is the [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types), not the file extension.

There is a reason why extensions are being banned. There is a silent agreement for a polyglot web development, where JavaScript isn't the center of everything. In the future, you will be able to import modules written in languages that are not JavaScript into your JavaScript code.

However, I made something that may be the solution you are looking for. I've made a simple server that runs on Node.js (which seems to be what you are using) that serves files **requested without extension with the proper MIME type**. You can get it at the following link:

https://github.com/frederico-miranda/simple-server/blob/master/simple-server.js

You can run it with the following command:

```
node simple-server.js
```

It will handle files without extension by trying to find a file that properly matches.

```
URL: /src/js/Text/index
Match: src/js/Text/index.js
Served with MIME type 'application/javascript'
```

I've tested your project on this. I've attached a screenshot.

![Screenshot_2020-01-30_10-48-11](https://user-images.githubusercontent.com/11416855/73455064-1bbb6f00-434e-11ea-9414-898ab6091fbb.png)

**Comment by Israel-Laguan** [comment]
I used [`serve`](https://github.com/zeit/serve#readme) package at the end.

Yet, I feel like somewhere must state that we can't use multiple files or `import` statements in the first project.

**Comment by jofer86** [comment]
@Israel-Laguan as this issue comes with a proposal and a specific solution I think the proper approach should be to raise a pull request with the description you provided here, and the proposed solution included in the README file, and maybe another .eslintrc.json file that includes the specific rules for the first two projects, that way the Microverse staff can merge it to the guidelines if deemed appropriate.

**Comment by MauricioRobayo** [comment]
I feel this has not been a pain point for most students, more of an edge case for more advanced ones, and the offending lines can be disabled with a comment if you decide to go this way.

Since there are no updates about this and it's been a while since the last comment, I'm closing it. Please reopen it if something else needs to be discussed, or open a PR as mentioned above.
