### ISSUE TITLE
linting errors in the Gemfile

### ISSUE THREAD

**Issue by keshav-c** [microverseinc/linters-config#53]
Rubocop raises some linting errors in the Gemfile, specifically

    Gemfile:43:28: C: Style/SymbolArray: 
    Use %i or %I for an array of symbols. 
    gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

    Gemfile:64:31: C: Style/SymbolArray: 
    Use %i or %I for an array of symbols. 
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

Attempting to fix, results in this error on bundle update

**There was an error parsing `Gemfile`: `:mri` is not a valid platform. ...**

Maybe Gemfile should be excluded from .rubocop.yml ?

**Comment by frederico-miranda** [comment]
I think that, if you follow Rubocop's suggestion, you'll be able to solve this issue.
There are two styles of making an array of symbols, and the style enforced by Rubocop is

```
# instead of:
[:mri, :mingw, :x64_mingw]

# do this, which is the same:
%i[mri mingw x64_mingw]
```

 I have left a screenshot as an example.
![Screenshot_2020-02-05_14-59-09](https://user-images.githubusercontent.com/11416855/73868919-15366700-4828-11ea-9c89-35383ad803f6.png)
