### ISSUE TITLE
issue with rubcop extension in visual studio code 

### ISSUE THREAD

**Issue by mohamednaser** [microverseinc/linters-config#54]
am using an extenstion called ruby-rubocop with visual studio editor 

but when trying to add the microverse linter for rails projects there is a notification appears contain the message 

.rubocop.yml: Layout/LineLength has the wrong namespace - should be Metrics Warning: unrecognized cop Layout/HashAlignment found in .rubocop.yml

**Comment by abruzy** [comment]
Hi @mohamednaser,

I experience this same issue as well but it has being fixed, check the new config file and try it.

You can reach out to me on slack @abruzy if you still face the problem. I'll be glad to help you out

**Comment by MauricioRobayo** [comment]
@mohamednaser Did you solve it? Can we close this issue?

**Comment by MauricioRobayo** [comment]
Closing it as there are no updates on this.
