### ISSUE TITLE
Automate reviews with GitHub Actions

### ISSUE THREAD

**Issue by MauricioRobayo** [microverseinc/linters-config#60]
Proposal to use [GitHub Actions](https://github.com/features/actions) instead of Stickler.

## Problem

When students submit their HTML&CSS projects, they have to wait a couple of hours to get feedback. 

Often, the feedback includes validating the HTML file. For that, the TSEs need to validate the files and then provide feedback so students can go on and validate the files themselves to find and fix the issues and then request another code review.

That’s a long process that could be automated.

Stickler does not provide the ability to run HTML validation, and since it is a black box, there is small room for customization, for example, https://github.com/microverseinc/linters-config/issues/56.

## GitHub Actions

We can run the CSS linter using GitHub actions, with the advantage that GHA is not a black box so we can install dependencies and customize to our needs as much as we want. There is also no need to enable anything from the student making it easier to use, just copy the [file](https://github.com/MauricioRobayo/gh-actions-html-css/blob/html-css-linters/.github/workflows/linters.yml) and GitHub will pick it up and run it.

Here is a test PR which runs Stylelint and html-validator: https://github.com/MauricioRobayo/gh-actions-html-css/pull/3

We can do a lot with GitHub actions to automate many of code-reviews processes. For example, the Ruby OOP Milestone 1 is checking the project setup. So we can run a Bash script to validate the required setup: https://github.com/MauricioRobayo/mv-oop1-gh-actions/pull/4

The students will have [immediate feedback](https://github.com/MauricioRobayo/mv-oop1-gh-actions/pull/4/checks?check_run_id=523571839) once they open a PR:

[![image](https://user-images.githubusercontent.com/2121481/77237881-f4d52880-6b99-11ea-852b-afc18fe9125e.png)](https://github.com/MauricioRobayo/mv-oop1-gh-actions/pull/4/checks?check_run_id=523571839)

In the end, a TSE should check the project and approve it or request changes, but most of the feedback will be already given making it a faster process for the student and a lighter one for the TSEs, so students will be able to move faster and TSEs will be able to cover more ground. 

And on top of all, students can add cool badges to their READMEs 😄 :

![Linters](https://github.com/MauricioRobayo/mv-oop1-gh-actions/workflows/Linters/badge.svg) ![Linters](https://github.com/MauricioRobayo/mv-oop1-gh-actions/workflows/Tests/badge.svg)

**Comment by gootyfer** [comment]
Hi @MauricioRobayo! Thanks a for the nice research work. I really liked the extra capabilities that this new tools would provide us, and the badges are a super cool extra ball.
Here are some concerns I want you to give some feedback about:
- First, I have a concern about vendor lock-in, since GHA is only available for GH, right? Stickler could be used in a different platform like Gitlab?
- Second, if we decide to go with this change: can you research how many things should we change? For sure, we'll need to update the docs of this `linters-config` repo. Anywhere else in Pathwright, capstone project requirements, etc.? Will you please research about it to estimate how much work will it take to switch to GHA?

Thanks again for being so proactively trying to improve students experience! 🙌

**Comment by MauricioRobayo** [comment]
Thanks, @gootyfer !

You are right, the vendor lock-in will be an issue. Currently, Stickler does not support GitLab or Bitbucket, but they might enable support at some point. This is from their [FAQ](https://stickler-ci.com/faq):

> Can I use Stickler CI with Bitbucket or Gitlab?
> Not currently. If there is enough demand in the future, support may be added.

I'll come back here when I have a more clear picture of how much work it will be to update the info on every place.

I think almost everything is referencing this repo, so this might be the bigger challenge, and there is a reference to Stickler which is pointing to this repo [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/). But I'll double-check more carefully and let you know when I'm more confident about the amount of work to be done.

**Comment by MauricioRobayo** [comment]
This initial solution had some issues with the HTML validator. After some research, I think I have a better implementation using [Webhint](https://webhint.io/) which can integrate the w3 HTML validation, plus some other additional validations. Also, I added the [Lighthouse](https://github.com/GoogleChrome/lighthouse-ci) report which I think can give a lot of insights for students.

Here is the more solid proposal, initially just for the HTML and CSS module: https://github.com/microverseinc/linters-config/pull/67.

**Comment by MauricioRobayo** [comment]
Thanks @gootyfer @nidalaa ! I think I can close this issue now. 😄
