### ISSUE TITLE
New cops warning

### ISSUE THREAD

**Issue by SevlaMare** [microverseinc/linters-config#65]
New cops by default will throw a Linter warning, that ask to enable or disable the new cops and it will make the code not pass in Stickler CI.

Following the documentation, use this configuration:
AllCops:
  NewCops: disable

Will be the best approach, otherwise after any update we go thought this error again and again.

But this configuration, for some reason, is throwing this error:
Warning: AllCops does not support NewCops parameter. 
In disagreement with documentation.

See more on https://docs.rubocop.org/en/latest/versioning/

**Comment by edwinmoradian90** [comment]
Agreed, dealing with this issue now, need to update the yml.

**Comment by MauricioRobayo** [comment]
Hi @SevlaMare  @edwinmoradian90 , there is already a PR to fix this: https://github.com/microverseinc/linters-config/pull/63.

You can add your thoughts on that one before it gets merged, and you can modify your `.rubocop.yml` according to what's discussed over there.

**Comment by MauricioRobayo** [comment]
The PR has been merged. Closing this.
