### ISSUE TITLE
The JavaScript eslint configuration has unnecesary steps

### ISSUE THREAD

**Issue by santiago-rodrig** [microverseinc/linters-config#68]
# Going through `eslint` questions takes time...

If you are going to overwrite the generated `.eslintrc.json` file then stepping through `npx eslint --init` is unnecessary, I suggest doing the following:
1. `npm i --save-dev eslint eslint-config-airbnb-base eslint-plugin-import`
2. downloading the file `.eslintrc.json`

If you think it's better the actual way of doing it then that's fine, but at least let me know why.

**Thanks for your time**.

**Comment by AdnanAfsari** [comment]
Hello @santiago-rodrig ✋ 

Nice catch 👏 .I think you are right 👍 .

Can you please make necessary changes and make a PR 😄 .

Thanks very much.
