### ISSUE TITLE
Invalid CSS properties are not getting caught by the CSS stylelint.

### ISSUE THREAD

**Issue by tirthajyoti-ghosh** [microverseinc/linters-config#78]
- Invalid CSS property values such as `background-color: red 5px solid;`, `margin-top: auto auto;`, `padding: auto;` are not getting flagged by the CSS stylelint.

**Comment by bolah2009** [comment]
@AdnanAfsari Would it be possible to check if `webhint` can do this? It seems https://jigsaw.w3.org/css-validator/ checks this, according to @tirthajyoti-ghosh 

Please, investigate this and discuss your findings here.

**Comment by bolah2009** [comment]
After some investigation, I think https://github.com/csstree/stylelint-validator can solve this as a plugin.

@tirthajyoti-ghosh  If you are up for it you can test it locally and if it works you can make necessary changes and open a PR? 

cc/ @AdnanAfsari

**Comment by AdnanAfsari** [comment]
**Mauricio's Suggestions** 

- [ ] We can add [it](https://github.com/csstree/stylelint-validator) to the current [stylelint configuration](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json)

- [ ] We should install [it](https://github.com/csstree/stylelint-validator) on the [GHA here](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml#L45)

- [ ] Update the Readme with the [local setup](https://github.com/microverseinc/linters-config/tree/master/html-css#stylelint) to also include that dependency for stylelint.

**Comment by bolah2009** [comment]
Open a PR [here](https://github.com/microverseinc/linters-config/pull/79)

Thanks, @tirthajyoti-ghosh for creating the issue, @MauricioRobayo for suggestions and @AdnanAfsari for your help. 🙇🏽‍♂️

Please feel free to check and leave comments
