### ISSUE TITLE
Colorize gem not working in Pull Request with Github Actions checks 

### ISSUE THREAD

**Issue by shubham14p3** [microverseinc/linters-config#80]
## Description of issue

I followed the instruction correctly, I was able to setup the linter-config.

NOw I wanted to add Colorize in my project , I bundle installed the Colorize 

which was present in my Gemfile as well as my germfile.lock as dependencies, 
The repo is working fine in my Local system

But when I created the pull request, I am seeing the following error:

```
  RSpec Report
##[error]Process completed with exit code 1.
Run rspec --force-color --format documentation

An error occurred while loading ./spec/after_colon_spec.rb. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require 'colorize'

LoadError:
  cannot load such file -- colorize
# ./lib/after_colon.rb:1:in `<top (required)>'
# ./spec/after_colon_spec.rb:2:in `require_relative'
# ./spec/after_colon_spec.rb:2:in `<top (required)>'

Finished in 0.00003 seconds (files took 0.16121 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

##[error]Process completed with exit code 1.
```

where I have added everything in proper channel and flow,
kindly find my pull request  https://github.com/shubham14p3/Ruby-capstone-project/pull/1

Note: I am having Stickler issue and Linter error as well, kindly ignore them, Kindly help me out with Test-Rspec, also when I tried to remove the Colorize, it worked for me, but I want to use Colorize. @santiago-rodrig 

## Possible solution

Add troubleshooting section [here](https://github.com/microverseinc/linters-config/blame/master/ruby/README.md) that explains issues like this with the possible solution

**Comment by bolah2009** [comment]
Hi @shubham14p3, I couldn't reproduce this issue locally too. But I tried recreating the issue by forking your repo.

The issue had to do with the `deployment` flag used for installing the bundle in the workflow config.

Remove the `--deployment` flag from [the test.yml file on Line16](https://github.com/shubham14p3/Ruby-capstone-project/blob/ca86784cc88bea7c933e329c0953f07e21bcf6ca/.github/workflows/tests.yml#L16)

```diff
        run: |
-          [ -f Gemfile ] && bundle --deployment
+          [ -f Gemfile ] && bundle
          gem install --no-document rspec:'~>3.0'
```


See passing screenshot from your forked repo below:

![image](https://user-images.githubusercontent.com/36057474/85558654-da8b6a80-b620-11ea-8b37-4a4444953737.png)

**Comment by bolah2009** [comment]
@AdnanAfsari There's a similar issue in the PR too https://github.com/AdedayoOpeyemi/Ruby-capstone-project/pull/2#issuecomment-650159452

I think we can add a FAQ about this for students to remove the `--deployment` flag if they are having this issue.

**Comment by bolah2009** [comment]
@shubham14p3 does the suggestion worked for you?

Also, I left the issue open so we can address it properly to avoid other students from having the same issue.

**Comment by shubham14p3** [comment]
Hi @bolah2009 it's worked just fine.
