### ISSUE TITLE
Github action unable to call Class and Module from inside Rspec file

### ISSUE THREAD

**Issue by AdedayoOpeyemi** [microverseinc/linters-config#81]
Github action unable to call Class and Module from inside Rspec file. This problem only happens on github. Code works fine in local machine. 

```
     NoMethodError:
       undefined method `after_colon_check' for AfterColon:Module
     # ./spec/after_colon_spec.rb:18:in `block (3 levels) in <top (required)>'

  3) AfterColon#after_colon_check It returns an empty array if the line passed conly contains a psuedocode
     Failure/Error: AfterColon.after_colon_check(file_details[113], 113, error_array)
     
     NoMethodError:
       undefined method `after_colon_check' for AfterColon:Module
     # ./spec/after_colon_spec.rb:23:in `block (3 levels) in <top (required)>'

  4) AfterColon#after_colon_check It returns an empty array if the line passed only contains a psuedocode
     Failure/Error: AfterColon.after_colon_check(file_details[110], 110, error_array)
     
     NoMethodError:
       undefined method `after_colon_check' for AfterColon:Module
     # ./spec/after_colon_spec.rb:28:in `block (3 levels) in <top (required)>'
```

Works if I use the` include Classname/Modulename`

**Comment by bolah2009** [comment]
Hi @AdedayoOpeyemi, thanks for opening this issue. Is this the PR https://github.com/AdedayoOpeyemi/Ruby-capstone-project/pull/2 to failing GHA?

**Comment by AdedayoOpeyemi** [comment]
Hi @bolah2009, I am not sure I understand your question

**Comment by bolah2009** [comment]
Hi @AdedayoOpeyemi sorry for not clarifying myself. The failed GitHub Action (GHA) that you posted the error messages, am asking which of your Pull request (PR) is the error from?

Would be better to see the whole project for more context.
Thanks

**Comment by AdedayoOpeyemi** [comment]
Hi, 
Thanks for the clarification. [https://github.com/AdedayoOpeyemi/Ruby-capstone-project/pull/2](https://github.com/AdedayoOpeyemi/Ruby-capstone-project/pull/2) is the link to the Pull request. As stated I had to use the include keyword to make it work.

**Comment by bolah2009** [comment]
Okay, thanks @AdedayoOpeyemi

**Comment by shshamim63** [comment]
Hi @AdedayoOpeyemi :wave: 
I just check the issue you were having, well the way you have generated tests for your modules. actually needs some refactoring. Whenever you are adding tests for modules that are included in a class you should test them by generating the class instance. If you refactor the test suppose for `afrer_colon_spec.rb` in the following way it will not generate the error.
```rb
require_relative '../lib/after_colon.rb'
require_relative '../lib/linter'

describe AfterColon do
  let(:file) { './style.css' }
  let(:error_array) { [] }
  let(:cont) { File.readlines('./style.css') }
  let(:checker) { LinterApp.new }

  describe '#after_colon_check' do
    it 'returns nil when all the colons on line has the right afterspace' do
      expect(checker.after_colon_check(cont[34], 34)).to eql(nil)
    end

    it 'It returns an error message when the colons do not have the right afterspace' do
      checker.after_colon_check(cont[136], 136)
      expect(checker.after_colon_check(cont[136], 136)).to eq("\e[0;36;49mNo space after colon on line 137\e[0m")
    end

    it 'It returns nil if the line passed conly contains a psuedocode' do
      expect(checker.after_colon_check(cont[113], 113)).to eq(nil)
    end

    it 'It returns an error if there is no space after the colon' do
      checker.after_colon_check(cont[110], 110)
      expect(checker.after_colon_check(cont[110], 110)).to eq("\e[0;36;49mNo space after colon on line 111\e[0m")
    end
  end
end
```
This will not render any error while doing linter check. For more info on how to test modules please go through this [article](https://mixandgo.com/learn/how-to-test-ruby-modules-with-rspec)
