### ISSUE TITLE
Stylelint Failling for rails Api-only applications

### ISSUE THREAD

**Issue by Tresor11** [microverseinc/linters-config#83]
The Stylelint configs work as expected with a normal rails application, ie run the checks on any CSS/SCSS file however an API-only application does not have any of those files the result is that eslint failing the checks and returning the following

`Error: No files matching the pattern "**/*.{css,scss}" were found.
    at /home/runner/work/final-capstone-api/rails-app/node_modules/stylelint/lib/standalone.js:211:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
##[error]Process completed with exit code 1.`

**Comment by bolah2009** [comment]
@Tresor11 for an API only app, you can remove the Stylelint config instead of having a PR with failing linter checks.

@AdnanAfsari could we add a FAQ section [here](https://github.com/microverseinc/linters-config/tree/master/ror) and add this information? 🤔

**Comment by shshamim63** [comment]
@bolah2009 should we add the FAQ section at the end of [this](https://github.com/microverseinc/linters-config/blob/master/ror/README.md).
We can add some info like,
___
# :rocket:  FAQ
#### - If you are building an API only Rails application
For API only Rails application you can remove the Stylelint config. To do so remove line no. 23 to 36 from the [linter.yml](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml) file.
___
What do you think? :eyes:

**Comment by bolah2009** [comment]
Since FAQ should be a form of question and answer, I don't think that format is good enough. What if we call it "Troubleshooting", also let's link the line number using a permalink instead of only referencing a line number that could change.
