### ISSUE TITLE
Installing rspec to run on github actions is not working

### ISSUE THREAD

**Issue by descholar-ceo** [microverseinc/linters-config#89]
### Description
I added [this rspec tests setup file](https://github.com/descholar-ceo/linters-config/blob/master/ruby/.github/workflows/tests.yml) to my `.github/workflows/` folder to let github actions run my tests whenever I push new codes to my PR, but it is giving me this error:
```bash
Run [ -f Gemfile ] && bundle --deployment
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /home/runner/work/telegram-bot/telegram-bot/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `<main>'
##[error]Process completed with exit code 1.
```

I tried to research how to fix this but did not find any clue, maybe something is wrong!

**Comment by shshamim63** [comment]
Hi @descholar-ceo :wave: 
Is your ruby version 2.7.* ?
You can confirm that running `ruby -v` in your terminal. 
If that is the case. Please make a slight update on your [test.yml](https://github.com/descholar-ceo/linters-config/blob/master/ruby/.github/workflows/tests.yml)
[ruby-version: 2.6.x](https://github.com/descholar-ceo/linters-config/blob/e1c8370b36c7ddc60123479e8b5a3b4b897ba6f5/ruby/.github/workflows/tests.yml#L13) to [ruby-version: 2.7.x]
Hope this will resolve the issue.

**Comment by descholar-ceo** [comment]
> Hi @descholar-ceo 
> Is your ruby version 2.7.* ?
> You can confirm that running `ruby -v` in your terminal.
> If that is the case. Please make a slight update on your [test.yml](https://github.com/descholar-ceo/linters-config/blob/master/ruby/.github/workflows/tests.yml)
> [ruby-version: 2.6.x](https://github.com/descholar-ceo/linters-config/blob/e1c8370b36c7ddc60123479e8b5a3b4b897ba6f5/ruby/.github/workflows/tests.yml#L13) to ruby-version: 2.7.x
> Hope this will resolve the issue.

Thank you so much man, you saved me a million times. I will close this issue then since the answer you gave me solved the problem.
