### ISSUE TITLE
Rubocop 0.88 error in .yml in local env

### ISSUE THREAD

**Issue by Oitur** [microverseinc/linters-config#93]
When I run rubocop without the .yml file it shows the usual behavior (tells me to correct lines in my code).

However, when I try to run it with the .yml, I get this error:

(/home/puma/projects/cvviewer/.rubocop.yml): mapping values are not allowed in this context at line 123 column 73
/home/puma/.gem/ruby/2.7.0/gems/psych-3.2.0/lib/psych.rb:454:in `parse'
/home/puma/.gem/ruby/2.7.0/gems/psych-3.2.0/lib/psych.rb:454:in `parse_stream'
/home/puma/.gem/ruby/2.7.0/gems/psych-3.2.0/lib/psych.rb:388:in `parse'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/yaml_duplication_checker.rb:11:in `check'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/config_loader.rb:205:in `check_duplication'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/config_loader.rb:61:in `load_yaml_configuration'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/config_loader.rb:40:in `load_file'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/config_store.rb:58:in `for_dir'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/config_store.rb:37:in `for_pwd'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/cli.rb:124:in `apply_default_formatter'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/lib/rubocop/cli.rb:40:in `run'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/exe/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/puma/.gem/ruby/2.7.0/gems/rubocop-0.88.0/exe/rubocop:12:in `<top (required)>'
/home/puma/.gem/ruby/2.7.0/bin/rubocop:23:in `load'
/home/puma/.gem/ruby/2.7.0/bin/rubocop:23:in `<main>'

I recently had to change my hard drive (thus reinstalling all the OS and stuff) and I noticed that now I'm running version 0.88 instead of 0.80, not sure if it's relevant. (or maybe I'm doing something wrong)

Anyway, I appreciate if you can help with this.

**Comment by shshamim63** [comment]
Hi @Oitur :wave: ,
Thank for opening the issue, I think the issue is generating because of the duplication file of rubocop.yml file. Can you double-check it. If that is not the case, would you like to share the repository link that you are facing the issues?

**Comment by Oitur** [comment]
>> would you like to share the repository link that you are facing the issues?

Well I'm having the issue on my local environment (I now realize that I did not include that particular info when opening the issue, sorry). The repo seems to be doing fine. I did not have this problem before I changed OS, which makes it a bit frustrating, since I like to check locally before I push to make sure I can have clean code in my repo.

**Comment by shshamim63** [comment]
Sounds like either something in the parser is broken on your system (reinstall to fix it) or there is something syntactically wrong with your YAML configuration. Without more info it is hard to provide suggestions.
