### ISSUE TITLE
CSS Link in --Troubleshooting Section-- is broken.

### ISSUE THREAD

**Issue by jubaan** [microverseinc/linters-config#98]
Clicking on the link takes you to a **404 Not Found Github Page**.

![image](https://user-images.githubusercontent.com/25774518/93538471-d61ad900-f913-11ea-957b-6d3002987384.png)

**Comment by shshamim63** [comment]
Hi @jubaan :wave: Thanks for opening the issue. Yes, the link is not rendering to the right section, because the directory name is not correct that was mentioned as the link section.
